### ISSUE TITLE
Week 12 Lab ready for grading!

### ISSUE THREAD

**Issue by btroxel-matc** [madisoncollege-it-programs/python-scripting-btroxel-matc#16]
The scripts to #1 are labeled "chat-client.py" and "chat-server.py".

The scripts to #2 are labeled "filetransfer-client.py" and "filetransfer-server.py". You can find their corresponding text files in the same directory named "ftransfer.txt" and "ftransferserver.txt".

Thank you again for your help!

**Comment by cethenmc** [comment]
Nice work here, Bryan!  8 out of 8.
