### ISSUE TITLE
Lab: "Your First Script" Ready for grading.

### ISSUE THREAD

**Issue by btroxel-matc** [madisoncollege-it-programs/python-scripting-btroxel-matc#2]
No questions.

**Comment by cethenmc** [comment]
Hi, Brian. I got to this assignment tonight yet. It works when pressing the play button, I am sure. However, I would like you to be able to run this from the command line. If your shbang line is in their correctly, then please go to week2 and execute the following command to modify the rights.

chmod u+x first-script.py

Then execute the file from command line.

./first-script.py

If it renders results, then...
1. add the file to staging (git add .)
2. commit the file to your local repo. (git commit -m "changes requested to run from command line")
3. push to the git hub repository (git push)
4. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by cethenmc** [comment]
I saw your separate ticket saying you pushed it.  It looks good!  Thanks for handling!
