### ISSUE TITLE
Week 3 string.py Ready for Grading

### ISSUE THREAD

**Issue by btroxel-matc** [madisoncollege-it-programs/python-scripting-btroxel-matc#3]
My script for the Week 3 lab is in week3/string.py

**Comment by cethenmc** [comment]
Next time it may help to download the Word document assignment.  Technically, you should have had spaces between every "][" in #12 and 13.  Additionally, you should have had the same number of spaces in #13 as there were dollar signs in #12.  Please be more careful in week 4.  I will deduct it in the future.  ~Chris
